Split cray-product0-catalog cm to main and sub cm
Cray-HPE/cray-product-catalog pull request #235
Opened 2023-06-14 12:50 UTC by lathanm

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Target branch correct
- [ ] Testing is appropriate and complete, if applicable
- [ ] Is a new version being released? Update https://github.com/Cray-HPE/cray-product-catalog/wiki/CSM-Compatibility-Matrix
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2023-06-14 14:12 UTC, arnab-muk-hpe requested changes

2023-06-14 14:12 UTC, arnab-muk-hpe commented on cray_product_catalog/catalog_update.py
> +def split_catalog_data(data, main_cm_data, sub_cm_data):
@lathanm instead of updating as reference, return the data, its confusing in python language. Folks with non python background will become confused.

2023-06-14 14:12 UTC, arnab-muk-hpe commented on cray_product_catalog/catalog_update.py
> +                ''' This part of code might be deleted if the migration of cray-product-catalog data
@lathanm , this logic has to be in a function (creation of config map)

2023-06-14 14:12 UTC, arnab-muk-hpe commented on cray_product_catalog/catalog_update.py
> +SUB_CM_FIELDS_LIST = ['component_versions']
i see a constant.py file, this can move there, if we are using as set , better to define as set.

2023-06-14 14:12 UTC, arnab-muk-hpe commented on cray_product_catalog/catalog_update.py
> +    for k in set(list(data.keys())) - set(SUB_CM_FIELDS_LIST):
this logic has a caveat, assume in main data we are getting few common keys, which has be present in both cm.
In that case those keys will be missing in product config map.

2023-06-14 14:12 UTC, arnab-muk-hpe commented on cray_product_catalog/catalog_update.py
> +SUB_CONFIG_MAP = CONFIG_MAP + "-" + PRODUCT
name of the variable can be, `PRODUCT_CONFIG_MAP `, instead of concatenation, you can use f"" -> string

2023-06-15 16:36 UTC, abhkumar5 commented on cray_product_catalog/catalog_update.py
> +    for k in set(list(data.keys())) - PRODUCT_CM_FIELDS:
```suggestion
    for k in set(data.keys()) - PRODUCT_CM_FIELDS:
```

2023-06-15 17:01 UTC, abhkumar5 commented on cray_product_catalog/catalog_update.py
> +    main_cm_data = {}
We can directly create dictionary with dict comprehension and return:

return {k:data[k] for k in set(data.keys())-PRODUCT_CM_FIELDS}, {k:data[k] for k in PRODUCT_CM_FIELDS}

2023-06-15 17:19 UTC, abhkumar5 commented on cray_product_catalog/catalog_update.py
> +PRODUCT_CONFIG_MAP = CONFIG_MAP + "-" + PRODUCT
Just a thought for scalability, we can create a tuple of CMs and then use this tuple in `main` inside a loop and create CMs. Also the function `split_catalog_data` shall return a tuple of main,product data. e.g. (main_data, prod_data)
```suggestion
CONFIG_MAP = (CONFIG_MAP, f"{CONFIG_MAP}-{PRODUCT}")
```

Main() will be something like this:

splitted_data = split_catalog_data(data)
for ind, cm in enumerate(CONFIG_MAP):
     update_config_map(splitted_data[ind], cm, CONFIG_MAP_NAMESPACE)

2023-06-15 17:22 UTC, abhkumar5 requested changes
There are few suggestions from my side.

2023-06-28 11:53 UTC, closed without merging

2023-06-28 11:53 UTC, lathanm commented
Closing as the change is migrated to the main repo