Feature/casm 4348 split config map
Cray-HPE/cray-product-catalog pull request #276
Opened 2023-08-07 16:35 UTC by lathanm

## Summary and Scope

- CASM-4350: To address the 1MiB size limit of Kubernetes ConfigMaps, the 
  `cray-product-catalog` Kubernetes ConfigMap is split into multiple smaller
  ConfigMaps with each product's `component_versions` data in its own ConfigMap.
  Modify the `catalog_update.py` script to update data across these ConfigMaps.
- CASM-4427: Implement a prototype to have granular query from main and sub ConfigMaps
- CASM-3981: Add S3 artifacts and Loftsman manifests to the Product Catalog schema
- CASM-4368: Delete Cray Product Catalog details from main and sub ConfigMaps for a particular
  product version.
- Added new argument `max_attempts` to `modify_config_map` function in
  [`catalog_delete.py`](cray_product_catalog/catalog_delete.py), because we need not retry 100
  times when read ConfigMap fails for a product ConfigMap.

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CASM-4350](https://jira-pro.it.hpe.com:8443/browse/CASM-4350), [CASM-4368](https://jira-pro.it.hpe.com:8443/browse/CASM-4368), [CASM-4427](https://jira-pro.it.hpe.com:8443/browse/CASM-4427)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

### Tested on:

- Unit tested on Build systems
- Tested on Lemon drop using dummy ConfigMaps with actual scripts.
- Functional tests with the cray-product-catalog container is pending.

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_   So far we have done testing via unit test cases with dummy config maps, before merging these changes we need to test this code on real cray-product-catalog (via containers).

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

- We should think/plan on backup of legacy config maps
- Migration of old config maps into split mode

## Pull Request Checklist

- [ ] Target branch correct
- [ ] Testing is appropriate and complete, if applicable
- [ ] Is a new version being released? Update https://github.com/Cray-HPE/cray-product-catalog/wiki/CSM-Compatibility-Matrix
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2023-08-08 09:34 UTC, arnab-muk-hpe approved these changes
Looks good to me @krabhi-hpe , @mharding-hpe and @haasken-hpe please do the needful.
This is the final PR.

2023-08-08 14:52 UTC, paulose-kuriakose approved these changes

2023-08-09 05:22 UTC, krabhi-hpe requested changes

2023-08-09 05:22 UTC, krabhi-hpe commented on cray_product_catalog/catalog_delete.py
> +# (C) Copyright 2023 Hewlett Packard Enterprise Development LP
Since its an old file:
```suggestion
# (C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP
```

2023-08-09 05:22 UTC, krabhi-hpe commented on tests/mock_update_catalog.py
> +# (C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP
```suggestion
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP

```

2024-02-08 19:39 UTC, closed without merging