CASM-4504: Add label "type=cray-product-catalog" for all cray-product-catalog related ConfigMaps
Cray-HPE/cray-product-catalog pull request #278
Opened 2023-08-10 14:31 UTC by lathanm

While creating ConfigMaps related to cray-product-catalog, add label "type=cray-product-catalog" so that we can query all ConfigMaps (main and sub ConfigMaps) in one shot using the label 

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Target branch correct
- [ ] Testing is appropriate and complete, if applicable
- [ ] Is a new version being released? Update https://github.com/Cray-HPE/cray-product-catalog/wiki/CSM-Compatibility-Matrix
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2023-08-10 14:50 UTC, arnab-muk-hpe requested changes

2023-08-10 14:50 UTC, arnab-muk-hpe commented on cray_product_catalog/catalog_update.py
bring the label from constants.py

2023-08-10 14:50 UTC, arnab-muk-hpe commented on cray_product_catalog/query.py
bring the label from constants.py

2023-08-10 14:50 UTC, arnab-muk-hpe commented on charts/cray-product-catalog/templates/configmap.yaml
Now i am thinking, if we create main config map as we are creating product ConfigMap.
We can discuss it within team.

2023-08-14 11:23 UTC, krabhi-hpe commented on cray_product_catalog/constants.py
> +PRODUCT_CATALOG_CONFIG_MAP_LABEL = 'type='+PRODUCT_CATALOG_CONFIG_MAP_NAME
I was thinking something like this and then use them directly :
`
PRODUCT_CATALOG_CONFIG_MAP_LABEL_KEY = 'type'
PRODUCT_CATALOG_CONFIG_MAP_LABEL = {PRODUCT_CATALOG_CONFIG_MAP_LABEL_KEY: PRODUCT_CATALOG_CONFIG_MAP_NAME}

PRODUCT_CATALOG_CONFIG_MAP_LABEL_STR = "{0}={1}".format(PRODUCT_CATALOG_CONFIG_MAP_LABEL_KEY, PRODUCT_CATALOG_CONFIG_MAP_NAME)
`

2023-09-05 05:11 UTC, lathanm commented on charts/cray-product-catalog/templates/configmap.yaml
Since the main ConfigMap will be created when cray-product-catalog is installed we need not add the logic to create main ConfigMap in the code

2023-09-05 05:26 UTC, krabhi-hpe approved these changes

2023-09-05 05:48 UTC, arnab-muk-hpe approved these changes

2023-09-05 05:49 UTC, merged