CASM-4727: Migrate all products to latest version of cpc
Cray-HPE/cray-product-catalog pull request #325
Opened 2024-07-11 11:06 UTC by Pankhuri-Rajesh

## Summary and Scope

The changes are related to the new format of cray-product-catalog . The PR involves changes for three JIRAs attached below.

Two of them are bug fixes (4741 and 4743).

The third one involves design change to make the format of cray-product-catalog after migration more efficient and compatible. (4731) 
More details are present in the JIRA regarding all the code changes.

Also there is a change in setup.py to make use of the cpc module in iuf-cli code .

## Issues and Related PRs

* Resolves [CASM-4731](https://jira-pro.it.hpe.com:8443/browse/CASM-4731), [CASM-4743](https://jira-pro.it.hpe.com:8443/browse/CASM-4743), [CASM-4741](https://jira-pro.it.hpe.com:8443/browse/CASM-4741)

### Tested on:

  * starlord

## Pull Request Checklist

- [x] Target branch correct
- [x] Testing is appropriate and complete, if applicable
- [ ] Is a new version being released? Update https://github.com/Cray-HPE/cray-product-catalog/wiki/CSM-Compatibility-Matrix
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2024-07-11 15:02 UTC, rajeshranganathan-hpe approved these changes

2024-07-15 16:32 UTC, mharding-hpe requested changes

2024-07-15 16:32 UTC, mharding-hpe commented on cray_product_catalog/catalog_delete.py
> +        """
Triple quotes should not be used for regular code comments (function/method/class/module docstrings are an exception).
```suggestion
        # Invoke __modify_product_cm function only if the product_cm is present

        # Before attempting to delete a ConfigMap, first verify if for the product there is a product_cm present or not.
        # If not, give a warning message and continue
```

2024-07-15 16:32 UTC, mharding-hpe commented on cray_product_catalog/migration/main.py
> +def is_migrated():
This should be a function docstring, not a comment above the function
```suggestion
def is_migrated():
   """
   Check if ConfigMap is already migrated.
   Returns True if so, False if not.
   """
```

2024-07-15 16:32 UTC, mharding-hpe commented on cray_product_catalog/migration/main.py
> +    # check if configmap has already been migrated
```suggestion
    # Check if ConfigMap has already been migrated
```

2024-07-15 16:33 UTC, mharding-hpe approved these changes

2024-07-15 16:39 UTC, mharding-hpe commented on cray_product_catalog/migration/main.py
> +    config_map_obj = ConfigMapDataHandler()
```suggestion
def is_migrated():
    """
    Check if ConfigMap is already migrated.
    Returns True if so, False if not.
    """
    config_map_obj = ConfigMapDataHandler()
```

2024-07-15 16:41 UTC, mharding-hpe approved these changes

2024-07-15 16:41 UTC, merged